### ISSUE TITLE
In Mobile Safari, The Menu Does Not Close When Selecting An Item

### ISSUE THREAD

**Issue by Zozman** [claviska/doxicity#3]
### Describe the bug

When selecting an item in the menu in mobile Safari, the menu does not close after selection.  This makes it difficult to then access the content selected.

### To Reproduce

1. Open the menu on https://doxicity.vercel.app
2. Select an item
3. Menu does not close after selection

### Demo

https://user-images.githubusercontent.com/1192364/167710986-a2c38c03-6495-449f-830c-d689c27c8fd8.MP4

### Browser / OS

- OS: iOS
- Browser: Mobile Safari (App-Integrated Webview)
- Browser version: iOS 15.4.1

**Comment by claviska** [comment]
Thanks for filing this. I noticed this myself earlier. Currently, the menu persists which is the intended behavior, but on mobile it’s extremely inconvenient. I think anything under maybe 768px needs to ignore that setting.

I’ll get this fixed soon.
