### ISSUE TITLE
Configurable base url

### ISSUE THREAD

**Issue by szaboat** [claviska/doxicity#7]
### What issue are you having?

I've built a documentation for my project with the tool and I'd like to host it under a specific folder on a server. For example

`https://awesome-sauce.com/docs/`

with the current hardcoded `/` references it's not possible to link properly the assets (`/` links to the absolute path of the domain). For example the logo links to the `https://awesome-sauce.com/`.

### Describe the solution you'd like

It would be nice to have a `baseURL` or other configuration where it can be set and used in all references.

### Describe alternatives you've considered

It can be handled by the server with some rewrite rules but it seems as a pretty basic configuration option to have.

**Comment by claviska** [comment]
I'd like to support this and I'd accept a PR to make it happen. It's pretty low priority on my personal TODO list, though.

**Comment by claviska** [comment]
This has been fixed in and will be available in 2.0.0-beta.4. Note that 2.0.0-beta is mostly a rewrite and includes a change in direction. The biggest change is that the theme is no longer integrated and the CLI has gone away (perhaps temporarily).

See the latest readme for more details.
